version: '3.8'

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: astro-app
    ports:
      - "4321:4321" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
