name: CD | Connect - deploy.sh 

on:
  push:
    branches:
      - preprod
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/enhanced-git
            if [ "${{ github.ref }}" = "refs/heads/prod" ]; then
              ./deploy-front.sh prod
            elif [ "${{ github.ref }}" = "refs/heads/preprod" ]; then
              ./deploy-front.sh preprod
            else
              echo "Branche non reconnue : ${{ github.ref }}"
              exit 1
            fi
